apiVersion: v1
kind: Service

metadata:
  name: service-nodeport

spec:
  selector:
    app: app-value
  ports:
  - port: 8080 # 다른 파드가 서비스에 접근하기 위해 사용하는 포트
    targetPort: 80 # 대상 파드가 트래픽을 전달하는 포트
    nodePort: 30010 # 서비스가 외부에 공개되는 포트
  type: NodePort
